# /.github/workflows/ci.yaml
# GitHub actions workflow

name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    strategy:
      matrix:
        node-version: [lts/*]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Check for lint/formatting errors
        run: |
          npm ci
          npm run lint
  test-node:
    name: Test in node.js
    strategy:
      matrix:
        node-version: [16, lts/*, latest]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run library tests
        run: |
          npm ci
          npm run test:lib
